### ISSUE TITLE
Making DIY (Do It Yourself) mode for developing packages or system.

### ISSUE THREAD

**Issue by iconized** [Snigdha-OS/snigdhaos-issues#1]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines](https://snigdha-os.github.io/documentation/introduction/contributing).

### Motivation

It is a better option to share your knowledge with others. I think making a learning or building path also help other users to contribute or developing their own environment. A new Window Manager is being developed by @IXINTL . It will be a good option that you create a sub-domain (For example: learn.snigdhaos.org or diy.snigdhaos.org) as diy instructions.

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by eshanized** [comment]
Sure! I will make a different section and anyone can share his/her knowledge on "DIY" section.
