### ISSUE TITLE
Found Error

### ISSUE THREAD

**Issue by d3v1l0n** [Snigdha-OS/snigdhaos-issues#3]
### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://snigdha-os.github.io/documentation/introduction/contributing).

### Prerequisites

- [X] Snigdha OS Mirror has been installed. [Install Snigdha OS Mirror top of Arch Based Linux](https://snigdha-os.github.io/blog/)
- [ ] I have read the console error message carefully (if applicable).
- [ ] I am not using virtual machine.

### Package Name

snigdhaos-bootloader-grub

### Description

Failure when building on clean chroot.

### Steps to reproduce

No need reproduction steps.

### Expected behavior

No error!

### Actual behavior

Build Failed in chroot!

### Your PC Specification

- CPU: i7 [e.g i5 1335U]
- RAM: 16 GB [e.g 2 GiB]
- STORAGE: 512 GB [e.g SSD/HDD]
- Snigdha OS Build: ARCTIC [e.g arctic]
- Snigdha OS Version: 5.0 Dev[e.g 4.5]

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by eshanized** [comment]
Which command did you use? 
```bash
makepkg -f -scr
```
use the above to build. Probably you did not make the archive.

**Comment by eshanized** [comment]
Let me know your issue was resolved! Till the issue will be opened!
