### ISSUE TITLE
Non Linux Respin/Reconfig

### ISSUE THREAD

**Issue by d3v1l0n** [Snigdha-OS/snigdhaos-issues#4]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines](https://snigdha-os.github.io/documentation/introduction/contributing).

### Description

Dear @eshanized 

Previously "Snigdha OS" was a respin of windows. I want to remake Snigdha OS windows version again. Can I have permission to make it? 

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by eshanized** [comment]
The answer is simply no. Snigdha OS will not go in any other mode. I aim to expand the ecosystem. It doesn’t mean a different env.

**Comment by d3v1l0n** [comment]
Sorry bhai🫣. @iconized has cleared!
