### ISSUE TITLE
Exception in read_config_file(): [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by d3v1l0n** [Snigdha-OS/snigdhaos-issues#5]
### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://snigdha-os.github.io/documentation/introduction/contributing).

### Prerequisites

- [X] I'm using the latest version of the package. Read [How to see package version in Snigdha OS?](https://snigdhaos.org/blog/check-package-version-on-snigdha-os/)
- [X] I have cleared the package cache and reinstalled the package. Read [How to clear package cache?](https://snigdhaos.org/blog/check-package-version-on-snigdha-os/)
- [X] I have checked for latest package update.
- [X] I have tried the `sudo pacman -Syyu` or `update` command.
- [X] I have read the console error message carefully (if applicable).
- [X] I am not using virtual machine.

### Package Name

snigdhaos-blackbox

### Description

Exception in read_config_file(): [Errno 2] No such file or directory: '/home/whoami/Documents/GitHub/snigdhaos-blackbox/usr/share/blackbox/defaults/blackbox.yaml'
2024-04-19 06:51:55:ERROR > Exception in Main() : g-file-error-quark: Failed to open file “/home/whoami/Documents/GitHub/snigdhaos-blackbox/usr/share/blackbox/images/snigdhaos-blackbox.png”: No such file or directory (4)
2024-04-19 06:51:55:INFO > App Started
Traceback (most recent call last):
  File "/home/whoami/Documents/GitHub/snigdhaos-blackbox/usr/share/blackbox/blackbox.py", line 436, in on_close
    settings = Settings(self.display_versions, self.display_package_progress)
                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Main' object has no attribute 'display_versions'

### Steps to reproduce

Just Run The Binary:
sudo /bin/python /home/whoami/snigdhaos-blackbox/usr/share/blackbox/blackbox.py

### Expected behavior

Run without error!

### Actual behavior

Exception in read_config_file(): [Errno 2] No such file or directory

### Your PC Specification

- CPU: i9 12th Gen [e.g i5 1335U]
- RAM: 32 GiB [e.g 2 GiB]
- STORAGE: 1 TB Nvme SSD[e.g SSD/HDD]
- Snigdha OS Build: ARCTIC [e.g arctic]
- Snigdha OS Version: 5.0.0 [e.g 4.5]

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by eshanized** [comment]
Thanks for contributing ❤️. We are looking into the issue🔥.
